### ISSUE TITLE
Выбор целей

### ISSUE THREAD

**Issue by rpavlovs** [alxdrlitreev/slavaukraine#1]
Торги на сегодня вроде как отменили, может новостные ресурсы есть смысл побомбить пока?

**Comment by rpavlovs** [comment]
а, нет, мосбиржу не отложили:
https://www.vedomosti.ru/finance/news/2022/02/28/911189-otkritii-torgov-mosbirzhe

**Comment by artemtam** [comment]
Выбираем цели мы сами по ситуации, сейчас поменяли на https://nsud.info.gov.ru/: https://github.com/alxdrlitreev/slavaukraine/commit/62316e41bbc08bacbd27c86de03216a55a27006e
